name: sqlite_orm_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  analyzer: ^5.7.1
  build: ^2.3.1
  source_gen: ^1.2.7
  sqlite_orm_annotation:
    path: ../sqlite_orm_annotation

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
